# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58dfe5dd915ed64c38936bc077559af317653d8298e19c6a59616d341b9823b570a573898bc0b1d4fa4a60031836abd2f4a6ca15f0a5d93e8876a9f5be856594

test:
  secret_key_base: 17edf3b5ce1afd18f86bb2f4f09120c73a47bd1b2cf11b1625b64ffb9f7f9ff3c2441070a51d3acee73b1b6f5368ef4e7b658238cf7d96f0b131e801fc68134d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
